name: Publish

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew publishAllPublicationsToMavenCentralRepository
      env:
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}

    - name: Generate XCFramework
      run: ./gradlew :xray-configuration:assembleXray-configurationReleaseXCFramework

    - name: Zip XCFramework
      run: |
          cd xray-configuration/build/XCFrameworks/release
          zip -r ../../../../XCFramework.zip xray_configuration.xcframework
      
    - name: Upload XCFramework to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: XCFramework.zip
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
